### ISSUE TITLE
Block GM/NPC Rolls

### ISSUE THREAD

**Issue by Sayshal** [FaeyUmbrea/ethereal-plane#1]
Hey, can I request a feature to block rolls from the GM or for "NPC" tokens to be filtered out. Especially with MidiQOL socket support it can get really spammy for mass-initiatives, etc. :)

**Comment by FaeyUmbrea** [comment]
Hi there. There already is a very simple filter in place that only allows public rolls to go through. For most applications this is sufficient because usually GM rolls are not public rolls unless you really want your players to see what you are doing.

**Comment by FaeyUmbrea** [comment]
Hello,
is the message visibility filter enough to cover your usecase or do you still need a blacklist/whitelist feature?
