### ISSUE TITLE
Issue: 10x the chat messages

### ISSUE THREAD

**Issue by TheAlexPlus** [FaeyUmbrea/ethereal-plane#2]
When a message gets posted to chat, it gets posted into the foundry stream chat 10 times.

I'm currently on V10.312
dnd5e 2.3.1

**Comment by FaeyUmbrea** [comment]
Hi there, thanks for reporting this.
This appears to be a bug in the actual server code, but I'm unsure what is causing this.
I'm currently rewriting most of the server, so for the time being I will have to restart the patreon server to mitigate this.

**Comment by TheAlexPlus** [comment]
Thanks for looking at it!  After I saw your comment it seemed to be fixed.

**Comment by FaeyUmbrea** [comment]
The underlying bug is not fixed, please give me a ping here if it occurs again until I close the issue.
