### ISSUE TITLE
Server.exe crashes when I make a roll

### ISSUE THREAD

**Issue by Jasper-J-R** [FaeyUmbrea/ethereal-plane#4]
When I am using ethereal plane, it works properly with chat messages, however when I roll a die the program crashes. The result of the die roll is displayed on my twitch chat, then the program immediately crashes. Any help would be appreciated.

**Comment by FaeyUmbrea** [comment]
Hi there, I need some more information here, what "program" is crashing exactly? What streaming platform are you using? What version of Foundry and the Module are you on? Do you have any error logs?

**Comment by Jasper-J-R** [comment]
The local bridge server is the program that is crashing, I am using twitch, foundry 11 and ethereal plane version 1.3.0. I will check the console for error logs, I didn't see any error logs near the local bridge exe.

**Comment by Jasper-J-R** [comment]
![image](https://github.com/FaeyUmbrea/ethereal-plane/assets/153030170/69aae31d-bda8-40fd-902f-73ee1d52ef26)
This is what is logged in the console when I try to roll a die

**Comment by FaeyUmbrea** [comment]
None of those are explaining any crashes. I would need the log output from the standalone client too. You can get that by executing it in CMD or Powershell instead of running the .exe directly.

**Comment by Jasper-J-R** [comment]
![image](https://github.com/FaeyUmbrea/ethereal-plane/assets/153030170/36cb5def-88f3-4b0a-ab2f-314b905006b2)

It appears as though the issue is that I haven't set up the youtube streaming stuff, but I don't use youtube streaming. Is there a way to disable that functionality?

**Comment by Jasper-J-R** [comment]
Simply commenting out the lines in the .env file with youtube seemed to do the trick.

**Comment by FaeyUmbrea** [comment]
Ah yeah that makes sense, sorry for the confusion

**Comment by Jasper-J-R** [comment]
No worries! It was a simple fix. I also appreciate the quick response!
